[package]
name = "client"
version = "0.1.0"
authors = ["Duncan Freeman <duncan.freeman1@gmail.com>"]
edition = "2021"

[dependencies]
egui = "0.28"
eframe = { version = "0.28", default-features = false, features = [
    "accesskit",
    "default_fonts",
    "glow",
    "persistence",
] }
log = "0.4"
serde = { version = "1", features = ["derive"] }
getrandom = { version = "0.2", features = ["js"] }

common = { path = "../common" }
tarpc = { version = "0.34.0", features = ["serde1"] }

ewebsock-tarpc = { path = "../../ewebsock-tarpc" }
#poll-promise = { version = "0.3.0", features = ["tokio"] }
poll-promise = { git = "https://github.com/Masterchef365/poll-promise.git", branch = "wasm", features = ["tokio"] }
futures-util = "0.3.30"


[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "1.32.0"
features = ["rt", "time", "rt-multi-thread"]

[target.'cfg(target_arch = "wasm32")'.dependencies.tokio]
version = "1.32.0"
features = ["rt", "macros"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
