[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
framework = { git = "https://github.com/Masterchef365/fckweb.git", branch = "main" }
serde = { version = "1", features = ["derive"] }
tarpc = { version = "0.34.0", features = ["serde1"] }
